version: '2'
services:
   
  services:
    container_name: serviceDB
    #image: mista123/servicesdbbase:latest
    build: .
    networks:
      - net
    ports:
      - 8080:8080

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:11.0.3
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    networks:
      - net
    ports:
      - 8081:8080
      

volumes:
  image-db:
    driver: local

networks:
  net:
    driver: bridge
